export const DarkTheme = {
    background: "#141313",
    fontFamilyMedium: "system-ui",
    fontFamilySrcMedium: 'system-ui',
    fontFamilyRegular: "system-ui",
    fontFamilySrcRegular: 'system-ui',
    fontFamilyBold: "system-ui",
    fontFamilySrcBold: 'system-ui',
    fontColor: 'white',
    inverseFontColor: '#58636b',
    fontSizeRegular: '2rem',
    fontSizeHeading: '2.5rem',
    borderColor: 'white',
    disabledFontColor: '#8598aa',
    controlBorderColor: 'white',
    inverseBackgroundColor: 'white',
    warningBackgroundColor: '#fafd0c', 
    successBackgroundColor: '#4cad51', 
    errorBackgroundColor: '#b50e06', 
    informationBackgroundColor: '#001ad6', 
    activeBackgroundColor: '#ffffff',
    activeFontColor: '#58636b',
    popupModalColor: '#00aae8',
    colorPalette: {
        green: '#5eb459',
        green1: '#4b8129',
        orange: '#9f7517',
        greenShadow: '#1c3539',
        yellow: '#fafd0c',
        yellowShadow: '#333832',
        red: '#b50e06',
        redShadow: '#2f1930',
        pink: '#f03ef3',
        pinkShadow: '#490f4a',
        blue: '#001ad6',
        blueShadow: '#021282',
    },
};
  